In [90]:
import numpy as np
from sklearn.ensemble import IsolationForest
y_train = np.genfromtxt("y_train.csv", delimiter=",")
features_train = np.genfromtxt("x_train_median.csv", delimiter=",", dtype='double')[1:]
features_test = np.genfromtxt("x_test_median.csv", delimiter=",")

In [91]:
features_train.shape

(1212, 833)

In [92]:
features_train = features_train[:,1:]

In [93]:
(features_train.shape , features_test.shape)

((1212, 832), (777, 833))

In [94]:
features_train

array([[1.08918762e+01, 8.32442812e+05, 2.05855441e+04, ...,
        1.03626330e+06, 8.53385585e+04, 1.03088664e+05],
       [1.15129936e+01, 8.32442898e+05, 2.05855248e+04, ...,
        1.00716322e+06, 9.56950206e+04, 1.05161109e+05],
       [1.10521848e+01, 8.32442896e+05, 2.05855128e+04, ...,
        1.01995544e+06, 8.02532999e+04, 1.04177052e+05],
       ...,
       [9.26732222e+00, 8.32442816e+05, 2.05855258e+04, ...,
        1.00787121e+06, 1.19139273e+05, 1.05240375e+05],
       [1.00000786e+01, 8.32442827e+05, 2.05855641e+04, ...,
        1.04786315e+06, 1.04741008e+05, 1.00272537e+05],
       [9.07080996e+00, 8.32442842e+05, 2.05855319e+04, ...,
        1.02989438e+06, 9.98021279e+04, 1.04448184e+05]])

In [89]:
features_train

array([[           nan,            nan,            nan, ...,
                   nan,            nan,            nan],
       [1.08918762e+01, 8.32442812e+05, 2.05855441e+04, ...,
        1.03626330e+06, 8.53385585e+04, 1.03088664e+05],
       [1.15129936e+01, 8.32442898e+05, 2.05855248e+04, ...,
        1.00716322e+06, 9.56950206e+04, 1.05161109e+05],
       ...,
       [9.26732222e+00, 8.32442816e+05, 2.05855258e+04, ...,
        1.00787121e+06, 1.19139273e+05, 1.05240375e+05],
       [1.00000786e+01, 8.32442827e+05, 2.05855641e+04, ...,
        1.04786315e+06, 1.04741008e+05, 1.00272537e+05],
       [9.07080996e+00, 8.32442842e+05, 2.05855319e+04, ...,
        1.02989438e+06, 9.98021279e+04, 1.04448184e+05]])

In [95]:
features_train

array([[1.08918762e+01, 8.32442812e+05, 2.05855441e+04, ...,
        1.03626330e+06, 8.53385585e+04, 1.03088664e+05],
       [1.15129936e+01, 8.32442898e+05, 2.05855248e+04, ...,
        1.00716322e+06, 9.56950206e+04, 1.05161109e+05],
       [1.10521848e+01, 8.32442896e+05, 2.05855128e+04, ...,
        1.01995544e+06, 8.02532999e+04, 1.04177052e+05],
       ...,
       [9.26732222e+00, 8.32442816e+05, 2.05855258e+04, ...,
        1.00787121e+06, 1.19139273e+05, 1.05240375e+05],
       [1.00000786e+01, 8.32442827e+05, 2.05855641e+04, ...,
        1.04786315e+06, 1.04741008e+05, 1.00272537e+05],
       [9.07080996e+00, 8.32442842e+05, 2.05855319e+04, ...,
        1.02989438e+06, 9.98021279e+04, 1.04448184e+05]])

### We use the Isolation Forest Anomaly detection method:

In [97]:
clf = IsolationForest(max_samples=10)
clf.fit(features_train)
features_trainNO = clf.predict(features_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/iforest.py:237: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/iforest.py:247: FutureWarning: behaviour="old" is deprecated and will be removed in version 0.22. Please use behaviour="new", which makes the decision_function change to match other anomaly detection algorithm API.
  FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/iforest.py:415: DeprecationWarning: threshold_ attribute is deprecated in 0.20 and will be removed in 0.22.
  " be removed in 0.22.", DeprecationWarning)


In [98]:
unique, counts = np.unique(features_trainNO, return_counts=True)
dict(zip(unique, counts))

{-1: 122, 1: 1090}

In [99]:
np.savetxt("features_trainNO.csv", features_trainNO, delimiter=",")